name: Run Postman Collection with Newman

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  newman:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Newman and HTML Reporter
      run: |
        npm install -g newman
        npm install -g newman-reporter-html

    - name: Run Postman Collection
      run: |
        newman run NotesAPI.postman_collection.json -e NotesAPIenvironment.postman_environment.json

    - name: Upload HTML Report
      uses: actions/upload-artifact@v3
      with:
        name: Newman HTML Report
        path: newman/report.html

